### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. (Parameter 'path')

### ISSUE THREAD

**Issue by EPinci** [MaxMelcher/AzureDevOps.WikiPDFExport#125]
Hello,

following the documentation, I executed the exe in the cloned repo's folder with no parameters but I'm getting:

```
00:00:00.30 ERR: Something bad happend.
System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.IO.DirectoryInfo..ctor(String path)
   at azuredevops_export_wiki.WikiPDFExporter.Export()
```

Am I missing something?

**Comment by MaxMelcher** [comment]
I am confident that this works now - let me know if not.
