### ISSUE TITLE
##[error]RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded

### ISSUE THREAD

**Issue by logjeferson** [MaxMelcher/AzureDevOps.WikiPDFExport#150]
When I run the export for a slightly larger number of wiki pages I receive the buffer limit error message:

System.ArgumentException: Markdown elements in the input are too deeply nested - depth limit exceeded. Input is most likely not sensible or is a very large table.

When I activate the debug I receive the log below:
##[error]RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded

Below are the complete debug logs:

##[debug]Evaluating condition for step: 'Export Wiki Files to PDF'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: Export Wiki Files to PDF
Task : A wrapper for the AzureDevOps.WikiPDFExport
Description : A wrapper for the AzureDevOps.WikiPDFExport
Version : 3.8.5
Author : Richard Fennell
Help : Version: 3.8.5. More Information
##[debug]Using node path: C:\agents\3.236.1\externals\node16\bin\node.exe
##[debug]agent.TempDirectory=D:\a_temp
##[debug]loading inputs and endpoints
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading INPUT_CLONEREPO
##[debug]loading INPUT_DOWNLOADPATH
##[debug]loading INPUT_EXTRAPARAMETERS
##[debug]loading INPUT_INJECTEXTRAHEADER
##[debug]loading INPUT_LOCALPATH
##[debug]loading INPUT_OUTPUTFILE
##[debug]loading INPUT_USEAGENTTOKEN
##[debug]loading INPUT_USEPRERELEASE
##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
##[debug]loading SECRET_UIPATHCLIENTID
##[debug]loading SECRET_UIPATHSECRETID
##[debug]loaded 14
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]repo=undefined
##[debug]localpath=D:\a\1\s\Internal-Documentation
##[debug]singleFile=undefined
##[debug]outputFile=D:\a\1\s\321067.pdf
##[debug]extraParameters=--verbose
##[debug]user=undefined
##[debug]password=undefined
##[debug]useAgentToken=true
##[debug]branch=undefined
##[debug]injectExtraHeader=False
##[debug]cloneRepo=false
##[debug]overrideExePath=undefined
##[debug]downloadPath=D:\a_temp
##[debug]rootExportPath=undefined
##[debug]usePreRelease=false
Defaulting variable rootExportPath as not defined
Variable: Repo [undefined]
Variable: Use Agent Token [true]
Variable: Username [undefined]
Variable: Password [*****]
Variable: LocalPath [D:\a\1\s\Internal-Documentation]
Variable: rootExportPath [D:\a\1\s\Internal-Documentation]
Variable: SingleFile [undefined]
Variable: OutputFile [D:\a\1\s\321067.pdf]
Variable: Branch [undefined]
Variable: InjectExtraHeader [false]
Variable: OverrideExePath [undefined]
Variable: UsePreRelease [false]
Variable: DownloadPath [D:\a_temp]
##[debug]AGENT.OS=Windows_NT
Starting download azuredevops-export-wiki.exe to D:\a_temp
Downloading MaxMelcher/AzureDevOps.WikiPDFExport@4.6.0...
Download done
##[debug]Agent environment resources - Disk: D:\ Available 11998.00 MB out of 14333.00 MB, Memory: Used 1923.00 MB out of 7167.00 MB, CPU: Usage 15.50%
##[debug]Agent environment resources - Disk: D:\ Available 11998.00 MB out of 14333.00 MB, Memory: Used 1839.00 MB out of 7167.00 MB, CPU: Usage 13.06%
Downloaded executable D:\a_temp\azuredevops-export-wiki.exe
Using the EXE path of 'D:\a_temp\azuredevops-export-wiki.exe' for AzureDevOps.WikiPDFExport
Processing the contents of the folder 'D:\a\1\s\Internal-Documentation'
Using D:\a\1\s\Internal-Documentation as the root path to export
Using the .order file in the root of the wiki to determine the order of the pages to export
Adding extra parameters to the command line
Changing folder to D:\a\1\s\Internal-Documentation
Using command '"D:\a_temp\azuredevops-export-wiki.exe" -p "D:\a\1\s\Internal-Documentation" -o "D:\a\1\s\321067.pdf" --verbose'
##[debug]Agent environment resources - Disk: D:\ Available 11998.00 MB out of 14333.00 MB, Memory: Used 1777.00 MB out of 7167.00 MB, CPU: Usage 11.28%
##[debug]Agent environment resources - Disk: D:\ Available 11998.00 MB out of 14333.00 MB, Memory: Used 1744.00 MB out of 7167.00 MB, CPU: Usage 9.93%
##[debug]Agent environment resources - Disk: D:\ Available 11998.00 MB out of 14333.00 MB, Memory: Used 1783.00 MB out of 7167.00 MB, CPU: Usage 8.87%
00:00:02.41 ERR: Something bad happend.
System.ArgumentException: Markdown elements in the input are too deeply nested - depth limit exceeded. Input is most likely not sensible or is a very large table.
at Markdig.Helpers.ThrowHelper.g__DepthLimitExceeded|16_0()
at Markdig.Renderers.RendererBase.WriteChildren(ContainerInline containerInline)
at Markdig.Renderers.Html.Inlines.DelimiterInlineRenderer.Write(HtmlRenderer renderer, DelimiterInline obj)
at Markdig.Renderers.MarkdownObjectRenderer2.Write(RendererBase renderer, MarkdownObject obj) at Markdig.Renderers.RendererBase.Write(MarkdownObject obj) at Markdig.Renderers.RendererBase.WriteChildren(ContainerInline containerInline) at Markdig.Renderers.RendererBase.Write(MarkdownObject obj) at Markdig.Renderers.Html.ParagraphRenderer.Write(HtmlRenderer renderer, ParagraphBlock obj) at Markdig.Renderers.MarkdownObjectRenderer2.Write(RendererBase renderer, MarkdownObject obj)
at Markdig.Renderers.RendererBase.Write(MarkdownObject obj)
at Markdig.Renderers.RendererBase.WriteChildren(ContainerBlock containerBlock)
at Markdig.Renderers.RendererBase.Write(MarkdownObject obj)
at Markdig.Renderers.TextRendererBase.Render(MarkdownObject markdownObject)
at azuredevops_export_wiki.MarkdownConverter.ConvertToHTML(IList`1 files)
at azuredevops_export_wiki.WikiPDFExporter.Export()

##[error]Error: Command failed: "D:\a_temp\azuredevops-export-wiki.exe" -p "D:\a\1\s\Internal-Documentation" -o "D:\a\1\s\321067.pdf" --verbose
##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;]Error: Command failed: "D:\a_temp\azuredevops-export-wiki.exe" -p "D:\a\1\s\Internal-Documentation" -o "D:\a\1\s\321067.pdf" --verbose

##[debug]task result: Failed
##[error]Error: Command failed: "D:\a_temp\azuredevops-export-wiki.exe" -p "D:\a\1\s\Internal-Documentation" -o "D:\a\1\s\321067.pdf" --verbose

##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;]Error: Command failed: "D:\a_temp\azuredevops-export-wiki.exe" -p "D:\a\1\s\Internal-Documentation" -o "D:\a\1\s\321067.pdf" --verbose
##[debug]Processed: ##vso[task.complete result=Failed;]Error: Command failed: "D:\a_temp\azuredevops-export-wiki.exe" -p "D:\a\1\s\Internal-Documentation" -o "D:\a\1\s\321067.pdf" --verbose

**Comment by MaxMelcher** [comment]
Typically that means that a table is not well-formatted. Run the converter locally and see what page causes this and then check the tables on that page.
