### ISSUE TITLE
Application crashes on Puppeteer

### ISSUE THREAD

**Issue by sandor-priva** [MaxMelcher/AzureDevOps.WikiPDFExport#157]
Most likely due to an update of chrome. 
Many thanks for helping!

00:00:01.30   WARN: File D:\source\iocontroller\testtools\wiki-export\Engineer.wiki\Home\Embedded.md is empty and will be skipped!
00:00:02.99 ERR: Something bad happend.
PuppeteerSharp.ProcessException: Failed to create connection
 ---> System.ObjectDisposedException: The semaphore has been disposed.
   at System.Threading.SemaphoreSlim.CheckDispose()
   at System.Threading.SemaphoreSlim.WaitAsync(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.SemaphoreSlim.WaitAsync()
   at PuppeteerSharp.Helpers.TaskQueue.Enqueue(Func`1 taskGenerator) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Helpers\TaskQueue.cs:line 32
   at PuppeteerSharp.Connection.SendAsync(String method, Object args, Boolean waitForCallback) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Connection.cs:line 134
   at PuppeteerSharp.Browser.CreateAsync(Connection connection, String[] contextIds, Boolean ignoreHTTPSErrors, ViewPortOptions defaultViewPort, LauncherBase launcher, Func`2 targetFilter, Action`1 initAction) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Browser.cs:line 530
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 76
   --- End of inner exception stack trace ---
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 85
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 91
   at azuredevops_export_wiki.PDFGenerator.ConvertHTMLToPDFAsync(SelfDeletingTemporaryFile tempHtmlFile)
   at azuredevops_export_wiki.WikiPDFExporter.Export()

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by devonuto** [comment]
00:00:03.93 ERR: Something bad happend.
PuppeteerSharp.ProcessException: Failed to launch browser! [0219/083016.255:FATAL:v8_initializer.cc(428)] Error loading V8 startup snapshot file
Backtrace:
        IsSandboxedProcess [0x00007FFBA1606202+1042002]
        IsSandboxedProcess [0x00007FFBA1582BB2+503810]
        IsSandboxedProcess [0x00007FFBA15922D0+567072]
        IsSandboxedProcess [0x00007FFBA1FD0ED4+11309860]
        IsSandboxedProcess [0x00007FFBA1FD0D1E+11309422]
        ovly_debug_event [0x00007FFBA040A4CB+28999179]
        ovly_debug_event [0x00007FFBA0409BB3+28996851]
        ovly_debug_event [0x00007FFBA0409D24+28997220]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FFBA15072BC+10409532]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FFBA1507180+10409216]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FFBA1506F8B+10408715]
        ChromeMain [0x00007FFB9E861226+390]
        GetPakFileHashes [0x00007FF7DE4B26D1+5841]
        GetPakFileHashes [0x00007FF7DE4B1B02+2818]
        GetHandleVerifier [0x00007FF7DE608092+936514]
        BaseThreadInitThunk [0x00007FFCB812E8D7+23]
        RtlUserThreadStart [0x00007FFCB987BF2C+44]


   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 83
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 89
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 68
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 91
   at azuredevops_export_wiki.PDFGenerator.ConvertHTMLToPDFAsync(SelfDeletingTemporaryFile tempHtmlFile)
   at azuredevops_export_wiki.WikiPDFExporter.Export()
